#
# GitLab CI configuration.
#
# https://docs.gitlab.com/ee/ci/yaml
#

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

stages:
  - 💿

default:
  tags:
    - cd-r.platform.hardware/x86-64.12
    - cd-r.platform.supervisor/linux.sysbox-runc.docker-engine
  # Using this instead of nixos/nix:latest to handle hardcoded dynamic linker paths.
  image: debian:unstable-slim
  before_script:
    # Install Nix with the Determinate Nix Installer. The `nix` command and flakes are enabled by default.
    #
    # https://github.com/DeterminateSystems/nix-installer#in-a-container
    - apt update -y
    - apt install curl git -y
    - curl --fail --location https://install.determinate.systems/nix --proto '=https' --show-error --silent --tlsv1.2 | sh -s -- install linux --extra-conf "sandbox = false" --init none --no-confirm
    - . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    # Create `nix.conf` + `.netrc` files and alias Git URLs.
    #
    # https://nix.dev/manual/nix/latest/command-ref/conf-file
    # https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file
    # https://git-scm.com/docs/git-config
    - mkdir --parents /etc/nix
    - |
      tee --append /etc/nix/nix.conf << END_OF_FILE
      access-tokens = ${CI_SERVER_HOST}=PAT:${CI_JOB_TOKEN}
      netrc-file = /etc/nix/.netrc
      END_OF_FILE
    - |
      tee --append /etc/nix/.netrc << END_OF_FILE
      machine ${CI_SERVER_HOST}
      login gitlab-ci-token
      password ${CI_JOB_TOKEN}
      END_OF_FILE
    - git config set --system --append url."${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_FQDN}".insteadOf "${CI_SERVER_URL}"
    - git config set --system --append url."${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_FQDN}".insteadOf "ssh://git@${CI_SERVER_SHELL_SSH_HOST}:${CI_SERVER_SHELL_SSH_PORT}"

#
# Jobs.
#

# Properties we can't set with `default`.
.default:
  stage: 💿
  environment:
    name: Production
    action: access

Create Package:
  extends:
    - .default
  parallel:
    matrix:
      - PYTHON_BINARY:
          - python3.9
          - python3.10
          - python3.11
          - python3.12
          - python3.13
  script:
    - |
      nix develop '.#"'${PYTHON_BINARY}'"' --command bash -c "
        cd multi-storage-explorer &&
        just build &&
        cd ../multi-storage-client &&
        just package
      "
  artifacts:
    paths:
      - multi-storage-client/dist/

Publish Package:
  extends:
    - .default
  needs:
    - job: Create Package
      artifacts: true
  parallel:
    matrix:
      - PYTHON_TAG: ["cp39", "cp310", "cp311", "cp312", "cp313"]
        WHEEL_ARCH: arm64
        WHEEL_OS: macosx
        ARTIFACTORY_ARCH: arm64
        ARTIFACTORY_OS: macosx
      - PYTHON_TAG: ["cp39", "cp310", "cp311", "cp312", "cp313"]
        WHEEL_ARCH: aarch64
        WHEEL_OS: manylinux
        ARTIFACTORY_ARCH: aarch64
        ARTIFACTORY_OS: linux
      - PYTHON_TAG: ["cp39", "cp310", "cp311", "cp312", "cp313"]
        WHEEL_ARCH: x86_64
        WHEEL_OS: manylinux
        ARTIFACTORY_ARCH: x86_64
        ARTIFACTORY_OS: linux
  variables:
    URM_ARTIFACTORY_URL: https://urm.nvidia.com/artifactory
    URM_ARTIFACTORY_PATH: sw-ngc-data-platform-pypi/multi-storage-client/${CI_COMMIT_TAG}/
    PYTHON_WHEEL_PATTERN: multi_storage_client-${CI_COMMIT_TAG}-${PYTHON_TAG}-*${WHEEL_OS}_*_${WHEEL_ARCH}*.whl
  script:
    # Hardcode "arch=any" temporarily to unblock publishing.
    - |
      nix develop --command bash -c "
        cd multi-storage-client &&
        jf rt search \
          --url ${URM_ARTIFACTORY_URL} \
          --user ${URM_ARTIFACTORY_USERNAME} \
          --password ${URM_ARTIFACTORY_PASSWORD} \
          --fail-no-op \
          ${URM_ARTIFACTORY_PATH}/${PYTHON_WHEEL_PATTERN} ||
        (
          jf rt upload \
            --url ${URM_ARTIFACTORY_URL} \
            --user ${URM_ARTIFACTORY_USERNAME} \
            --password ${URM_ARTIFACTORY_PASSWORD} \
            --detailed-summary \
            --fail-no-op \
            --flat \
            --quiet \
            --target-props 'component_name=multi_storage_client;version=${CI_COMMIT_TAG};python-tag=${PYTHON_TAG};arch=any;os=${ARTIFACTORY_OS};changelist=${CI_COMMIT_SHORT_SHA};branch=release;release_approver=${GITLAB_USER_LOGIN};release_status=ready' \
            dist/${PYTHON_WHEEL_PATTERN} \
            ${URM_ARTIFACTORY_PATH}
        )
      "

Publish GitHub:
  extends:
    - .default
  needs:
    - job: Create Package
      artifacts: false
  variables:
    # Clones can't be shallow when pushing.
    #
    # https://docs.gitlab.com/ee/ci/runners/configure_runners.html#shallow-cloning
    GIT_DEPTH: 0
    GIT_PUSH_REFERENCES: refs/tags/${CI_COMMIT_TAG}
  rules:
    # Only mirror the default branch for latest releases, not backport releases.
    - if: $CI_COMMIT_TAG_MESSAGE == "latest"
      variables:
        # Tags must be dereferenced to commits when pushing to branches.
        #
        # https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt-emltrevgtlttypegtemegemv0998commitem
        GIT_PUSH_REFERENCES: refs/tags/${CI_COMMIT_TAG} refs/tags/${CI_COMMIT_TAG}^{commit}:refs/heads/${CI_DEFAULT_BRANCH}
  script:
    - |
      nix develop --command bash -c "
        eval $(ssh-agent -s)
        mkdir --parents ~/.ssh &&
        chmod 644 ${GITHUB_SSH_PUBLIC_KEY_FINGERPRINTS} &&
        cp -p ${GITHUB_SSH_PUBLIC_KEY_FINGERPRINTS} ~/.ssh/known_hosts &&
        chmod 400 ${GITHUB_DEPLOY_SSH_PRIVATE_KEY} &&
        ssh-add ${GITHUB_DEPLOY_SSH_PRIVATE_KEY} &&
        git push --atomic --force git@github.com:NVIDIA/multi-storage-client.git ${GIT_PUSH_REFERENCES}
      "
