{
 "title": "MSFS Dashboard",
 "description": "USE metrics dashboard for presenting Prometheus metrics scraped from an MSFS instance.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values({\"$job\"=\"$job\"},$job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Read Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hits",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - increase(fission_read_cache_waits_total{instance=\"dev:9088\", job=\"msfs\"}[10s])/clamp_min(increase(fission_read_cache_hits_total{instance=\"dev:9088\", job=\"msfs\"}[10s]),0.0000000001) - increase(fission_read_cache_misses_total{instance=\"dev:9088\", job=\"msfs\"}[10s])/clamp_min(increase(fission_read_cache_hits_total{instance=\"dev:9088\", job=\"msfs\"}[10s]),0.0000000001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waits",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(fission_read_cache_waits_total{instance=\"dev:9088\", job=\"msfs\"}[10s])/clamp_min(increase(fission_read_cache_hits_total{instance=\"dev:9088\", job=\"msfs\"}[10s]),0.0000000001)\n",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Misses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(fission_read_cache_misses_total{instance=\"dev:9088\", job=\"msfs\"}[10s])/clamp_min(increase(fission_read_cache_hits_total{instance=\"dev:9088\", job=\"msfs\"}[10s]),0.0000000001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true
  },
  {
   "title": "Read File Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 1, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(backend_read_file_success_latency_seconds_bucket{instance=\"dev:9088\", job=\"msfs\"}[5s])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(backend_read_file_success_latency_seconds_bucket{instance=\"dev:9088\", job=\"msfs\"}[5s])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(backend_read_file_success_latency_seconds_bucket{instance=\"dev:9088\", job=\"msfs\"}[5s])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(backend_read_file_success_latency_seconds_bucket{instance=\"dev:9088\", job=\"msfs\"}[5s])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Stat Directory Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(backend_stat_directory_success_latency_seconds_bucket{instance=\"dev:9088\", job=\"msfs\"}[5s])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(backend_stat_directory_success_latency_seconds_bucket{instance=\"dev:9088\", job=\"msfs\"}[5s])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(backend_stat_directory_success_latency_seconds_bucket{instance=\"dev:9088\", job=\"msfs\"}[5s])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(backend_stat_directory_success_latency_seconds_bucket{instance=\"dev:9088\", job=\"msfs\"}[5s])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Stat File Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 1, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(backend_stat_file_success_latency_seconds_bucket{instance=\"dev:9088\", job=\"msfs\"}[5s])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(backend_stat_file_success_latency_seconds_bucket{instance=\"dev:9088\", job=\"msfs\"}[5s])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(backend_stat_file_success_latency_seconds_bucket{instance=\"dev:9088\", job=\"msfs\"}[5s])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(backend_stat_file_success_latency_seconds_bucket{instance=\"dev:9088\", job=\"msfs\"}[5s])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "List Directory Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(backend_list_directory_success_latency_seconds_bucket{instance=\"dev:9088\", job=\"msfs\"}[5s])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(backend_list_directory_success_latency_seconds_bucket{instance=\"dev:9088\", job=\"msfs\"}[5s])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(backend_list_directory_success_latency_seconds_bucket{instance=\"dev:9088\", job=\"msfs\"}[5s])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(backend_list_directory_success_latency_seconds_bucket{instance=\"dev:9088\", job=\"msfs\"}[5s])))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}